server:
  port: 8080

spring:
  application:
    name: PlexMetadataManager
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always
    auto-startup: true
    overwrite-existing-jobs: true
    scheduler-name: ${spring.application.name}
    startup-delay: 10s
    wait-for-jobs-to-complete-on-shutdown: false
    properties:
      org:
        quartz:
          jobStore:
            #如果不需要将调度命令（例如添加和删除triggers）绑定到其他事务，那么可以通过使用 JobStoreTX 管理事务
            class: org.springframework.scheduling.quartz.LocalDataSourceJobStore
            #通知 JobStore 使用的表前缀
            tablePrefix: QRTZ_
            misfireThreshold: 12000
            #是否加入集群
            isClustered: true
            ##容许的最大作业延长时间
            clusterCheckinInterval: 20000
            maxMisfiresToHandleAtATime: 1
            txIsolationLevelSerializable: false
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool  #quartz 使用的线程池类型，org.quartz.spi.ThreadPool
            threadCount: 20   #线程池中的线程总个数，表示最多可以同时执行的个任务/作业个数
            threadPriority: 5   #线程优先级
            threadsInheritContextClassLoaderOfInitializingThread: true #线程继承初始化线程的上下文类加载器
          scheduler:
            #实例id设置为自动获取，集群下的所有调度器实例id 必须为唯一.
            instanceId: AUTO

management:
  health:
    db:
      enabled: true
    redis:
      enabled: true
    defaults:
      enabled: true
pagehelper:
  support-methods-arguments: true
  reasonable: true
  page-size-zero: true
logging:
  config: classpath:logback-spring.xml